import Phaser from 'phaser';
import { GameInput } from './Input';
import { FEATHER_POSITIONS, MOB_SPAWNS, PLATFORMS, REGIONS, WORLD_W, freshSave, loadSave, writeSave, maxHp, meleeDamage, eggDamage, moveMultiplier, xpToNext, type SaveData, type PlayerStats } from './types';

const evt=(name:string,detail:unknown={})=>window.dispatchEvent(new CustomEvent(name,{detail}));

export class GameScene extends Phaser.Scene{
  private controls!:GameInput; private player!:Phaser.Physics.Arcade.Sprite; private ground!:Phaser.Physics.Arcade.StaticGroup;
  private enemies!:Phaser.Physics.Arcade.Group; private eggs!:Phaser.Physics.Arcade.Group; private save!:SaveData;
  private face=1; private jumpHeld=false; private attackHeld=false; private powerHeld=false; private shootHeld=false; private inv=0; private attackCd=0; private powerCd=0; private shootCd=0; private region=-1; private boss?:Phaser.Physics.Arcade.Sprite; private bossHp=24; private started=0; private done=false;
  private skillHandler=(e:Event)=>this.upgrade((e as CustomEvent).detail.key as keyof PlayerStats);
  constructor(){super('game')}

  create(data:{continue?:boolean}){
    this.save=data?.continue&&loadSave()?loadSave()!:freshSave(); this.started=this.time.now; this.controls=new GameInput(); this.makeTextures();
    this.physics.world.setBounds(0,0,WORLD_W,900); this.cameras.main.setBounds(0,0,WORLD_W,900); this.cameras.main.setBackgroundColor('#153b35');
    this.ground=this.physics.add.staticGroup();
    for(const [x,y,w,h] of PLATFORMS){const p=this.ground.create(x+w/2,y+h/2,'block') as Phaser.Physics.Arcade.Image;p.setDisplaySize(w,h).setTint(0x327c3f).refreshBody();}
    this.decorate();
    this.player=this.physics.add.sprite(this.save.checkpoint.x,this.save.checkpoint.y,'hero').setDepth(10).setSize(48,66).setCollideWorldBounds(true);this.physics.add.collider(this.player,this.ground);this.cameras.main.startFollow(this.player,true,.08,.08,0,50);
    this.enemies=this.physics.add.group(); for(const m of MOB_SPAWNS){const s=this.enemies.create(m.x,m.y,m.kind) as Phaser.Physics.Arcade.Sprite;s.setData({hp:m.hp,xp:m.xp||15,home:m.x,kind:m.kind}).setSize(45,38).setCollideWorldBounds(true);this.physics.add.collider(s,this.ground);}
    this.physics.add.overlap(this.player,this.enemies,(_p,e)=>this.hurt((e as Phaser.Physics.Arcade.Sprite).x));
    this.eggs=this.physics.add.group({allowGravity:false});this.physics.add.overlap(this.eggs,this.enemies,(a,b)=>{const egg=a as Phaser.Physics.Arcade.Sprite, enemy=b as Phaser.Physics.Arcade.Sprite;if(!egg.active||!enemy.active)return;egg.destroy();this.hitEnemy(enemy,eggDamage(this.save.stats));});
    for(let i=0;i<FEATHER_POSITIONS.length;i++){if(this.save.feathers.includes(i))continue;const f=this.physics.add.image(FEATHER_POSITIONS[i].x,FEATHER_POSITIONS[i].y,'feather').setData('id',i).setDepth(8);f.body!.setAllowGravity(false);this.physics.add.overlap(this.player,f,(_p,o)=>this.collect(o as Phaser.Physics.Arcade.Image));}
    this.boss=this.physics.add.sprite(8910,535,'boss').setData('hp',this.bossHp).setSize(105,115).setDepth(9).setCollideWorldBounds(true);this.physics.add.collider(this.boss,this.ground);this.physics.add.overlap(this.player,this.boss,()=>this.hurt(this.boss!.x));this.physics.add.overlap(this.eggs,this.boss,(a)=>{(a as Phaser.Physics.Arcade.Sprite).destroy();this.hitBoss(eggDamage(this.save.stats));});if(this.save.bossDefeated)this.boss.disableBody(true,true);
    window.addEventListener('skill-upgrade',this.skillHandler);this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>window.removeEventListener('skill-upgrade',this.skillHandler));
    this.save.hp=Math.max(1,Math.min(this.save.hp,maxHp(this.save.stats)));this.pushHud();this.updateRegion(true);this.toast('Level 1 · Sprung, Schlag, Eischuss und Stampfer aktiv');
  }

  update(_t:number,ms:number){if(this.done)return;const dt=Math.min(.04,ms/1000),i=this.controls.poll(),b=this.player.body as Phaser.Physics.Arcade.Body, grounded=b.blocked.down||b.touching.down;this.inv=Math.max(0,this.inv-dt);this.attackCd=Math.max(0,this.attackCd-dt);this.powerCd=Math.max(0,this.powerCd-dt);this.shootCd=Math.max(0,this.shootCd-dt);
    const mul=moveMultiplier(this.save.stats);b.setMaxVelocity(350*mul,850);b.setAccelerationX(Math.abs(i.x)>.12?i.x*1500*mul:0);b.setDragX(grounded?1000:100);if(Math.abs(i.x)>.12){this.face=i.x>0?1:-1;this.player.setFlipX(this.face<0)}
    if(i.jump&&!this.jumpHeld&&grounded){b.setVelocityY(-570);this.jumpHeld=true}if(!i.jump)this.jumpHeld=false;
    if(i.attack&&!this.attackHeld&&this.attackCd<=0){this.melee();this.attackHeld=true}if(!i.attack)this.attackHeld=false;
    if(i.power&&!this.powerHeld&&grounded&&this.powerCd<=0){this.stomp();this.powerHeld=true}if(!i.power)this.powerHeld=false;
    if(i.shoot&&!this.shootHeld&&this.shootCd<=0){this.shoot();this.shootHeld=true}if(!i.shoot)this.shootHeld=false;
    this.player.setAlpha(this.inv>0&&Math.floor(this.time.now/80)%2?.35:1);this.updateEnemies();this.updateBoss(dt);this.updateRegion(false);if(this.player.y>850)this.respawn();this.save.playTime+=dt;
  }

  private makeTextures(){const g=this.add.graphics().setVisible(false),mk=(k:string,w:number,h:number,fn:()=>void)=>{if(this.textures.exists(k))return;g.clear();fn();g.generateTexture(k,w,h)};mk('block',8,8,()=>g.fillStyle(0xffffff).fillRect(0,0,8,8));mk('hero',72,82,()=>{g.fillStyle(0x4d352d).fillCircle(32,34,25).fillRoundedRect(12,32,42,43,15);g.fillStyle(0xb98a68).fillEllipse(31,32,26,19);g.fillStyle(0x111111).fillCircle(25,27,3).fillCircle(38,27,3);g.fillStyle(0x1aa6a2).fillRoundedRect(50,27,17,39,6);g.fillStyle(0xf15c83).fillRect(52,23,12,7).fillRect(58,10,7,16);});mk('feather',28,38,()=>{g.fillStyle(0xffdc4c).fillEllipse(11,14,17,27);g.fillStyle(0xfff2a1).fillTriangle(11,1,22,15,11,28);g.lineStyle(3,0x85531f).lineBetween(11,13,20,36)});
    const mob=(k:string,c:number)=>mk(k,58,48,()=>{g.fillStyle(c).fillRoundedRect(6,10,46,32,13);g.fillStyle(0xffffff).fillCircle(16,17,5);g.fillStyle(0x111111).fillCircle(15,17,2);g.fillStyle(0x241b18).fillRect(12,39,10,7).fillRect(38,39,10,7)});mob('beetle',0x496ea5);mob('boar',0x9b5143);mob('toucan',0x332f2d);mob('idol',0x7b714e);mob('snake',0x5d9146);mob('monkey',0x8b5b36);mk('egg',24,18,()=>g.fillStyle(0xffffff).fillEllipse(12,9,22,16).fillStyle(0xffe4a0).fillEllipse(8,6,6,4));mk('boss',132,138,()=>{g.fillStyle(0x4d3a51).fillRoundedRect(12,28,108,103,32);g.fillStyle(0x302333).fillCircle(66,40,44);g.fillStyle(0xff4657).fillTriangle(31,41,56,47,36,55).fillTriangle(101,41,76,47,96,55);g.fillStyle(0xe2c769).fillTriangle(26,24,42,2,55,28).fillTriangle(55,22,70,0,84,23).fillTriangle(82,28,105,4,113,36)});}
  private decorate(){const g=this.add.graphics().setDepth(-2);for(const r of REGIONS){g.fillStyle(r.sky).fillRect(r.x,0,r.width,900);g.fillStyle(r.ground,.28).fillRect(r.x,560,r.width,340)}for(let x=120;x<WORLD_W;x+=260){g.fillStyle(0x3c2b20).fillRect(x,500,15,190);g.fillStyle(0x1e6a39,.75).fillCircle(x+8,485,48)}}
  private melee(){this.attackCd=.28;for(const o of this.enemies.getChildren()){const e=o as Phaser.Physics.Arcade.Sprite;if(e.active&&Math.abs(e.x-this.player.x)<95&&Math.abs(e.y-this.player.y)<70&&Math.sign(e.x-this.player.x)===this.face)this.hitEnemy(e,meleeDamage(this.save.stats));}if(this.boss?.active&&Math.abs(this.boss.x-this.player.x)<120)this.hitBoss(meleeDamage(this.save.stats));}
  private stomp(){this.powerCd=1.1;this.cameras.main.shake(180,.012);for(const o of this.enemies.getChildren()){const e=o as Phaser.Physics.Arcade.Sprite;if(e.active&&Phaser.Math.Distance.Between(e.x,e.y,this.player.x,this.player.y)<175)this.hitEnemy(e,1+meleeDamage(this.save.stats));}if(this.boss?.active&&Phaser.Math.Distance.Between(this.boss.x,this.boss.y,this.player.x,this.player.y)<190)this.hitBoss(1+meleeDamage(this.save.stats));}
  private shoot(){this.shootCd=Math.max(.24,.62-(this.save.stats.agility-1)*.025);const e=this.eggs.create(this.player.x+this.face*38,this.player.y-8,'egg') as Phaser.Physics.Arcade.Sprite;e.setVelocityX(this.face*(520+this.save.stats.eggPower*8));e.setData('born',this.time.now);this.time.delayedCall(1800,()=>{if(e.active)e.destroy()});}
  private hitEnemy(e:Phaser.Physics.Arcade.Sprite,dmg:number){const hp=(e.getData('hp') as number)-dmg;e.setData('hp',hp).setTintFill(0xffffff);this.time.delayedCall(80,()=>e.active&&e.clearTint());if(hp<=0){const xp=e.getData('xp') as number;e.disableBody(true,true);this.addXp(xp)}}
  private hurt(x:number){if(this.inv>0||this.done)return;this.inv=1.15;const dmg=Math.max(1,2-Math.floor((this.save.stats.defense-1)/3));this.save.hp-=dmg;this.player.setVelocity((this.player.x<x?-1:1)*300,-290);evt('health',{hp:this.save.hp,maxHp:maxHp(this.save.stats)});if(this.save.hp<=0)this.time.delayedCall(450,()=>this.respawn())}
  private respawn(){this.save.hp=maxHp(this.save.stats);this.player.setPosition(this.save.checkpoint.x,this.save.checkpoint.y).setVelocity(0,0);this.inv=1.4;this.pushHud();this.toast('Zur letzten gespeicherten Position zurück')}
  private collect(f:Phaser.Physics.Arcade.Image){const id=f.getData('id') as number;if(this.save.feathers.includes(id))return;this.save.feathers.push(id);f.disableBody(true,true);this.addXp(8);writeSave(this.save);evt('feathers',{count:this.save.feathers.length,total:30});this.toast(`Kronenfeder ${this.save.feathers.length}/30`)}
  private updateEnemies(){for(const o of this.enemies.getChildren()){const e=o as Phaser.Physics.Arcade.Sprite;if(!e.active)continue;const d=this.player.x-e.x,home=e.getData('home') as number,kind=e.getData('kind') as string;const body=e.body as Phaser.Physics.Arcade.Body;if(Math.abs(d)<300)e.setVelocityX(Math.sign(d)*(kind==='snake'?160:kind==='boar'?130:80));else e.setVelocityX(Math.sign(home-e.x)*45);e.setFlipX(d<0);if(kind==='monkey'&&Math.abs(d)<230&&body.blocked.down&&Math.random()<.012)e.setVelocityY(-390);}}
  private updateBoss(dt:number){if(!this.boss?.active||this.save.bossDefeated)return;if(this.player.x>8520){evt('boss',{show:true,hp:this.bossHp/24,name:'DER HOHLKÖNIG'});const d=this.player.x-this.boss.x;this.boss.setVelocityX(Math.sign(d)*(this.bossHp<9?180:95));if((this.boss.body as Phaser.Physics.Arcade.Body).blocked.down&&Math.random()<dt*(this.bossHp<9?1.8:.8))this.boss.setVelocityY(-430);}}
  private hitBoss(dmg:number){if(!this.boss?.active||this.player.x<8400)return;this.bossHp-=dmg;evt('boss',{show:true,hp:Math.max(0,this.bossHp)/24,name:'DER HOHLKÖNIG'});this.cameras.main.shake(90,.006);if(this.bossHp<=0){this.boss.disableBody(true,true);this.save.bossDefeated=true;this.save.level2Unlocked=true;this.addXp(180);writeSave(this.save);evt('boss',{show:false});this.done=true;evt('victory',{time:Math.floor((this.time.now-this.started)/1000),feathers:this.save.feathers.length});}}
  private addXp(n:number){this.save.stats.xp+=n;while(this.save.stats.xp>=xpToNext(this.save.stats.level)){this.save.stats.xp-=xpToNext(this.save.stats.level);this.save.stats.level++;this.save.stats.skillPoints+=2;this.save.hp=maxHp(this.save.stats);this.toast(`LEVEL ${this.save.stats.level}! +2 Skillpunkte`)}writeSave(this.save);evt('rpg',{stats:this.save.stats,next:xpToNext(this.save.stats.level)});}
  private upgrade(k:keyof PlayerStats){if(k==='level'||k==='xp'||k==='skillPoints'||this.save.stats.skillPoints<1)return;const v=this.save.stats[k];if(typeof v!=='number')return;(this.save.stats[k] as number)=v+1;this.save.stats.skillPoints--;this.save.hp=Math.min(maxHp(this.save.stats),this.save.hp+1);writeSave(this.save);this.pushHud();this.toast(`${String(k)} verbessert`)}
  private updateRegion(force:boolean){const idx=REGIONS.findIndex(r=>this.player.x>=r.x&&this.player.x<r.x+r.width);if(idx>=0&&(force||idx!==this.region)){this.region=idx;const r=REGIONS[idx];this.save.checkpoint={x:Math.max(150,r.x+120),y:520};writeSave(this.save);evt('region',{name:r.name,objective:r.objective});}}
  private pushHud(){evt('hud',{hp:this.save.hp,maxHp:maxHp(this.save.stats),feathers:this.save.feathers.length,total:30});evt('rpg',{stats:this.save.stats,next:xpToNext(this.save.stats.level)})}
  private toast(message:string){evt('toast',{message})}
}
