import Phaser from 'phaser';
import { GameInput } from './Input';
import { freshSave, loadSave, writeSave, maxHp, meleeDamage, eggDamage, moveMultiplier, xpToNext, type SaveData, type PlayerStats } from './types';
const evt=(name:string,detail:unknown={})=>window.dispatchEvent(new CustomEvent(name,{detail}));

type EKind='snake'|'monkey'|'idol'|'toucan'|'boar'|'beetle';
const RUINS:[number,number,number,number][]=[[0,690,620,130],[700,610,330,210],[1120,525,290,295],[1500,650,380,170],[1970,570,310,250],[2380,480,300,340],[2770,610,390,210],[3260,535,300,285],[3650,650,380,170],[4120,565,320,255],[4520,690,680,130]];
const FEATHERS=[[480,560],[1250,405],[2500,360],[3420,415],[4260,440]] as const;
const SPAWNS:[EKind,number,number,number][]=[['snake',760,560,3],['beetle',980,560,3],['monkey',1180,470,5],['boar',1580,600,6],['toucan',1780,400,4],['idol',2050,510,7],['snake',2260,510,3],['monkey',2440,420,5],['beetle',2680,430,4],['boar',2850,560,6],['toucan',3070,390,4],['idol',3310,480,7],['snake',3540,500,4],['monkey',3750,590,5],['boar',3970,590,6],['toucan',4190,430,4],['idol',4380,500,7],['snake',4620,630,4],['beetle',4750,630,4],['monkey',4880,620,6]];

export class Level2Scene extends Phaser.Scene{
  private inputMap!:GameInput;private player!:Phaser.Physics.Arcade.Sprite;private platforms!:Phaser.Physics.Arcade.StaticGroup;private enemies!:Phaser.Physics.Arcade.Group;private eggs!:Phaser.Physics.Arcade.Group;private save!:SaveData;
  private facing=1;private inv=0;private jumpHeld=false;private attackHeld=false;private powerHeld=false;private shootHeld=false;private attackCd=0;private powerCd=0;private shootCd=0;private boss?:Phaser.Physics.Arcade.Sprite;private bossHp=36;private bossClock=0;private phase=1;private done=false;private started=0;
  private skillHandler=(e:Event)=>this.upgrade((e as CustomEvent).detail.key as keyof PlayerStats);
  constructor(){super('level2')}
  create(){this.save=loadSave()||freshSave();this.inputMap=new GameInput();this.started=this.time.now;this.makeTextures();this.physics.world.setBounds(0,0,5200,900);this.cameras.main.setBounds(0,0,5200,900);this.cameras.main.setBackgroundColor('#10261b');this.drawRuins();
    this.platforms=this.physics.add.staticGroup();for(const [x,y,w,h] of RUINS){const p=this.platforms.create(x+w/2,y+h/2,'ruinblock') as Phaser.Physics.Arcade.Image;p.setDisplaySize(w,h).refreshBody();}
    const cp=this.save.level2Checkpoint||{x:150,y:550};this.player=this.physics.add.sprite(cp.x,cp.y,'mokuhero').setDepth(10).setSize(48,66).setCollideWorldBounds(true);this.physics.add.collider(this.player,this.platforms);this.cameras.main.startFollow(this.player,true,.08,.08,0,55);
    this.enemies=this.physics.add.group();SPAWNS.forEach(([kind,x,y,hp],id)=>{const e=this.enemies.create(x,y,kind) as Phaser.Physics.Arcade.Sprite;e.setData({hp,xp:18+hp*3,kind,home:x,id}).setSize(44,38).setCollideWorldBounds(true);this.physics.add.collider(e,this.platforms)});this.physics.add.overlap(this.player,this.enemies,(_a,b)=>this.hurt((b as Phaser.Physics.Arcade.Sprite).x,2));
    this.eggs=this.physics.add.group({allowGravity:false});this.physics.add.overlap(this.eggs,this.enemies,(a,b)=>{const egg=a as Phaser.Physics.Arcade.Sprite,e=b as Phaser.Physics.Arcade.Sprite;if(!egg.active||!e.active)return;egg.destroy();this.hitEnemy(e,eggDamage(this.save.stats))});
    FEATHERS.forEach(([x,y],id)=>{if(this.save.level2Feathers.includes(id))return;const f=this.physics.add.image(x,y,'sunfeather').setData('id',id).setDepth(8);f.body!.setAllowGravity(false);this.physics.add.overlap(this.player,f,(_a,b)=>this.collect(b as Phaser.Physics.Arcade.Image));this.tweens.add({targets:f,y:y-12,duration:800+id*90,yoyo:true,repeat:-1})});
    this.boss=this.physics.add.sprite(4930,530,'mossboss').setSize(118,125).setDepth(9).setCollideWorldBounds(true);this.physics.add.collider(this.boss,this.platforms);this.physics.add.overlap(this.player,this.boss,()=>this.hurt(this.boss!.x,3));this.physics.add.overlap(this.eggs,this.boss,a=>{(a as Phaser.Physics.Arcade.Sprite).destroy();this.hitBoss(eggDamage(this.save.stats))});if(this.save.level2BossDefeated)this.boss.disableBody(true,true);
    window.addEventListener('skill-upgrade',this.skillHandler);this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>window.removeEventListener('skill-upgrade',this.skillHandler));this.save.hp=Math.min(Math.max(1,this.save.hp),maxHp(this.save.stats));this.pushHud();evt('region',{name:'RUINEN VON MOKU',objective:'Sammle 5 Sonnenfedern und besiege den Mooswächter'});this.toast('Level 2 · Ruinen von Moku');}

  update(_t:number,ms:number){if(this.done)return;const dt=Math.min(.04,ms/1000),i=this.inputMap.poll(),b=this.player.body as Phaser.Physics.Arcade.Body,grounded=b.blocked.down||b.touching.down;this.inv=Math.max(0,this.inv-dt);this.attackCd=Math.max(0,this.attackCd-dt);this.powerCd=Math.max(0,this.powerCd-dt);this.shootCd=Math.max(0,this.shootCd-dt);const mul=moveMultiplier(this.save.stats);b.setMaxVelocity(360*mul,860);b.setAccelerationX(Math.abs(i.x)>.12?i.x*1580*mul:0);b.setDragX(grounded?1050:110);if(Math.abs(i.x)>.12){this.facing=i.x>0?1:-1;this.player.setFlipX(this.facing<0)}if(i.jump&&!this.jumpHeld&&grounded){b.setVelocityY(-600);this.jumpHeld=true}if(!i.jump)this.jumpHeld=false;if(i.attack&&!this.attackHeld&&this.attackCd<=0){this.melee();this.attackHeld=true}if(!i.attack)this.attackHeld=false;if(i.power&&!this.powerHeld&&grounded&&this.powerCd<=0){this.stomp();this.powerHeld=true}if(!i.power)this.powerHeld=false;if(i.shoot&&!this.shootHeld&&this.shootCd<=0){this.shoot();this.shootHeld=true}if(!i.shoot)this.shootHeld=false;this.player.setAlpha(this.inv>0&&Math.floor(this.time.now/70)%2?.35:1);this.updateEnemies();this.updateBoss(dt);if(this.player.y>850)this.respawn();if(this.player.x>1500&&this.save.level2Checkpoint.x<1500)this.checkpoint(1580);if(this.player.x>3200&&this.save.level2Checkpoint.x<3200)this.checkpoint(3300);this.save.playTime+=dt;}

  private makeTextures(){const g=this.add.graphics().setVisible(false),mk=(k:string,w:number,h:number,f:()=>void)=>{if(this.textures.exists(k))return;g.clear();f();g.generateTexture(k,w,h)};mk('ruinblock',8,8,()=>g.fillStyle(0x63775b).fillRect(0,0,8,8));mk('mokuhero',72,82,()=>{g.fillStyle(0x4e352d).fillCircle(32,34,25).fillRoundedRect(12,32,42,43,15);g.fillStyle(0xb98a68).fillEllipse(31,32,26,19);g.fillStyle(0x151313).fillCircle(25,27,3).fillCircle(38,27,3);g.fillStyle(0x1aa6a2).fillRoundedRect(50,27,17,39,6);g.fillStyle(0xf15c83).fillRect(52,23,12,7).fillRect(58,10,7,16)});mk('sunfeather',30,40,()=>{g.fillStyle(0xffb72f).fillEllipse(12,15,18,29);g.fillStyle(0xffff9a).fillTriangle(12,1,24,16,12,30);g.lineStyle(3,0x8f5520).lineBetween(12,13,21,38)});const mob=(k:string,c:number)=>mk(k,58,48,()=>{g.fillStyle(c).fillRoundedRect(6,10,46,32,13);g.fillStyle(0xe9f6dd).fillCircle(16,17,5);g.fillStyle(0x101510).fillCircle(15,17,2);g.fillStyle(0x2a2018).fillRect(12,39,10,7).fillRect(38,39,10,7)});mob('snake',0x598b3d);mob('monkey',0x8b5b36);mob('idol',0x7b714e);mob('toucan',0x36302c);mob('boar',0x995143);mob('beetle',0x496ea5);mk('egg',24,18,()=>g.fillStyle(0xffffff).fillEllipse(12,9,22,16).fillStyle(0xffe1a0).fillEllipse(8,6,6,4));mk('mossboss',146,150,()=>{g.fillStyle(0x31543b).fillRoundedRect(12,34,122,108,34);g.fillStyle(0x517459).fillCircle(73,44,49);g.fillStyle(0xa9cf61).fillCircle(34,32,18).fillCircle(112,38,22).fillCircle(76,12,21);g.fillStyle(0xff7a3f).fillTriangle(35,48,62,53,40,62).fillTriangle(111,48,84,53,106,62);g.fillStyle(0x182318).fillEllipse(73,87,48,24)});}
  private drawRuins(){const g=this.add.graphics().setDepth(-4);g.fillGradientStyle(0x16382c,0x16382c,0x07140d,0x07140d).fillRect(0,0,5200,900);for(let x=100;x<5200;x+=210){g.fillStyle(0x244831,.65).fillRect(x,250+(x%4)*55,32,440);g.fillStyle(0x6f7f63,.45).fillRect(x-15,250+(x%4)*55,62,20);g.fillStyle(0x5ca44c,.35).fillCircle(x+15,280+(x%3)*80,45)}for(let x=500;x<5000;x+=630){g.lineStyle(8,0x9fc85a,.24).lineBetween(x,0,x-90,260)}}
  private melee(){this.attackCd=.25;for(const o of this.enemies.getChildren()){const e=o as Phaser.Physics.Arcade.Sprite;if(e.active&&Math.abs(e.x-this.player.x)<100&&Math.abs(e.y-this.player.y)<70&&Math.sign(e.x-this.player.x)===this.facing)this.hitEnemy(e,meleeDamage(this.save.stats))}if(this.boss?.active&&Math.abs(this.boss.x-this.player.x)<130)this.hitBoss(meleeDamage(this.save.stats))}
  private stomp(){this.powerCd=.95;this.cameras.main.shake(200,.014);for(const o of this.enemies.getChildren()){const e=o as Phaser.Physics.Arcade.Sprite;if(e.active&&Phaser.Math.Distance.Between(e.x,e.y,this.player.x,this.player.y)<190)this.hitEnemy(e,1+meleeDamage(this.save.stats))}if(this.boss?.active&&Phaser.Math.Distance.Between(this.boss.x,this.boss.y,this.player.x,this.player.y)<210)this.hitBoss(1+meleeDamage(this.save.stats))}
  private shoot(){this.shootCd=Math.max(.21,.55-(this.save.stats.agility-1)*.024);const e=this.eggs.create(this.player.x+this.facing*38,this.player.y-8,'egg') as Phaser.Physics.Arcade.Sprite;e.setVelocityX(this.facing*(550+this.save.stats.eggPower*9));this.time.delayedCall(1700,()=>{if(e.active)e.destroy()})}
  private hitEnemy(e:Phaser.Physics.Arcade.Sprite,dmg:number){const hp=(e.getData('hp') as number)-dmg;e.setData('hp',hp).setTintFill(0xffffff);this.time.delayedCall(70,()=>e.active&&e.clearTint());if(hp<=0){const xp=e.getData('xp') as number;e.disableBody(true,true);this.addXp(xp)}}
  private updateEnemies(){for(const o of this.enemies.getChildren()){const e=o as Phaser.Physics.Arcade.Sprite;if(!e.active)continue;const d=this.player.x-e.x,kind=e.getData('kind') as string,home=e.getData('home') as number,b=e.body as Phaser.Physics.Arcade.Body;if(Math.abs(d)<330)e.setVelocityX(Math.sign(d)*(kind==='snake'?180:kind==='boar'?145:kind==='monkey'?120:85));else e.setVelocityX(Math.sign(home-e.x)*50);e.setFlipX(d<0);if((kind==='monkey'||kind==='idol')&&Math.abs(d)<230&&b.blocked.down&&Math.random()<.013)e.setVelocityY(-410)}}
  private hurt(x:number,raw:number){if(this.inv>0||this.done)return;this.inv=1.15;const dmg=Math.max(1,raw-Math.floor((this.save.stats.defense-1)/3));this.save.hp-=dmg;this.player.setVelocity((this.player.x<x?-1:1)*320,-300);evt('health',{hp:this.save.hp,maxHp:maxHp(this.save.stats)});if(this.save.hp<=0)this.time.delayedCall(450,()=>this.respawn())}
  private respawn(){this.save.hp=maxHp(this.save.stats);this.player.setPosition(this.save.level2Checkpoint.x,this.save.level2Checkpoint.y).setVelocity(0,0);this.inv=1.5;writeSave(this.save);this.pushHud();this.toast('Moku-Speicherstein aktiviert')}
  private checkpoint(x:number){this.save.level2Checkpoint={x,y:520};writeSave(this.save);this.toast('Ruinen-Speicherstein gesichert')}
  private collect(f:Phaser.Physics.Arcade.Image){const id=f.getData('id') as number;if(this.save.level2Feathers.includes(id))return;this.save.level2Feathers.push(id);f.disableBody(true,true);this.addXp(18);writeSave(this.save);evt('feathers',{count:this.save.level2Feathers.length,total:5});this.toast(`Sonnenfeder ${this.save.level2Feathers.length}/5`)}
  private updateBoss(dt:number){if(!this.boss?.active||this.save.level2BossDefeated)return;if(this.player.x<4500)return;this.phase=this.bossHp>24?1:this.bossHp>12?2:3;evt('boss',{show:true,hp:this.bossHp/36,name:`MOOSWÄCHTER · PHASE ${this.phase}`});this.bossClock-=dt;if(this.bossClock<=0){this.bossClock=this.phase===1?1.45:this.phase===2?.95:.58;const d=this.player.x-this.boss.x;this.boss.setVelocityX(Math.sign(d)*(this.phase===3?290:190)).setVelocityY(-260-this.phase*55);this.cameras.main.shake(80,.004+this.phase*.002)}}
  private hitBoss(dmg:number){if(!this.boss?.active||this.player.x<4400)return;if(this.save.level2Feathers.length<3){this.toast('Der Wächter ist versiegelt · sammle mindestens 3 Sonnenfedern');return}this.bossHp-=dmg;evt('boss',{show:true,hp:Math.max(0,this.bossHp)/36,name:`MOOSWÄCHTER · PHASE ${this.phase}`});if(this.bossHp<=0){this.boss.disableBody(true,true);this.save.level2BossDefeated=true;this.addXp(260);writeSave(this.save);evt('boss',{show:false});this.done=true;evt('level2-victory',{level:this.save.stats.level,time:Math.floor((this.time.now-this.started)/1000)})}}
  private addXp(n:number){this.save.stats.xp+=n;while(this.save.stats.xp>=xpToNext(this.save.stats.level)){this.save.stats.xp-=xpToNext(this.save.stats.level);this.save.stats.level++;this.save.stats.skillPoints+=2;this.save.hp=maxHp(this.save.stats);this.toast(`LEVEL ${this.save.stats.level}! +2 Skillpunkte`)}writeSave(this.save);evt('rpg',{stats:this.save.stats,next:xpToNext(this.save.stats.level)})}
  private upgrade(k:keyof PlayerStats){if(k==='level'||k==='xp'||k==='skillPoints'||this.save.stats.skillPoints<1)return;const v=this.save.stats[k];if(typeof v!=='number')return;(this.save.stats[k] as number)=v+1;this.save.stats.skillPoints--;this.save.hp=Math.min(maxHp(this.save.stats),this.save.hp+1);writeSave(this.save);this.pushHud();this.toast(`${String(k)} verbessert`)}
  private pushHud(){evt('hud',{hp:this.save.hp,maxHp:maxHp(this.save.stats),feathers:this.save.level2Feathers.length,total:5});evt('rpg',{stats:this.save.stats,next:xpToNext(this.save.stats.level)})}
  private toast(message:string){evt('toast',{message})}
}
